import Head from 'next/head'
import { useRouter } from 'next/dist/client/router'

const GlobalHeader = () => {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Patrick Marsceill — This Modern Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {router.pathname === '/' ? (
        <h1>This Modern Web</h1>
      ) : (
        <div>This Modern Web</div>
      )}
      <p>The personal website of Patrick Marsceill</p>
    </>
  )
}

export default GlobalHeader
